---
name: URI-Title-iTMS
version: 0.5
author:
  - Tom Insam <tom@jerakeen.org>
abstract: Get titles from itms:// urls
license: perl
requires:
  Net::iTMS: 0
  URI::Title: 1
provides:
  URI::Title::iTMS:
    file: lib/URI/Title/iTMS.pm
    version: 0.5
generated_by: Module::Build version 0.2608
